version: '3'

services:
  front:
    container_name: niji
    restart: always
    image: svelte-niji
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ".:/app"
    ports:
      - "80:3000"