version: '3'

services:
  front:
    container_name: svelte-front
    restart: always
    image: svelte-front-image
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"